# Generated by Django 6.0.6 on 2026-08-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tbl_training_courses',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=50)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RegistrationDate', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentService.trainingcourse')),
            ],
            options={
                'db_table': 'tbl_student_details',
            },
        ),
    ]
