# Generated by Django 6.0.6 on 2026-08-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateField()),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMode', models.CharField(max_length=30)),
                ('PaymentDescription', models.CharField(max_length=200)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentService.studentdetails')),
            ],
            options={
                'db_table': 'tbl_student_payments',
            },
        ),
    ]
