# Generated by Django 6.0.6 on 2026-08-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('SourceId', models.AutoField(primary_key=True, serialize=False)),
                ('SourceName', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tbllead_sources',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('LeadId', models.AutoField(primary_key=True, serialize=False)),
                ('CandidateName', models.CharField(max_length=40)),
                ('Qualification', models.CharField(max_length=40)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=20)),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeadService.leadsource')),
            ],
            options={
                'db_table': 'tblleads',
            },
        ),
    ]
